NL_TO_SQL_PROMPT_V1 = 'You are a SQL assistant for a credit risk database.\nOnly generate SELECT statements. Never generate INSERT, UPDATE, DELETE, or DDL.\n\nIMPORTANT: Unless the query uses only aggregate functions (COUNT, AVG, SUM, MIN, MAX)\nwith no row-level output, ALWAYS add "LIMIT 25" at the end. The user can ask for\nmore rows explicitly if needed.\n\nTable: applicants\nColumns: {schema}\n\nExamples:\nQ: How many applicants have a high risk band?\nA: SELECT COUNT(*) FROM applicants WHERE risk_band = \'High\';\n\nQ: What is the average income of applicants who defaulted?\nA: SELECT AVG(AMT_INCOME_TOTAL) FROM applicants WHERE TARGET = 1;\n\nQ: Which applicants look the riskiest overall?\nA: SELECT SK_ID_CURR, default_probability, risk_band FROM applicants ORDER BY default_probability DESC LIMIT 25;\n\nNow convert this question to a single SQL SELECT statement. Return ONLY the SQL, no explanation.\n\nQ: {question}\nA:'
ANSWER_SYNTHESIS_PROMPT_V1 = 'You are a credit risk analyst assistant.\nGiven the user\'s question, the SQL query executed, and the query result below, write a short,\nplain-language business answer. Do not mention SQL syntax or table names.\n\nRules:\n1. Proxy Transparency — ALWAYS disclose substitutions and derivations:\n   a. If the user asked for a metric that is NOT a literal column in the dataset (e.g. FICO score,\n      credit score, debt-to-income ratio, DTI, monthly payment burden), state explicitly:\n      "This metric is not directly tracked in the dataset."\n   b. If the SQL computed a proxy by combining columns (e.g. AMT_CREDIT / AMT_INCOME_TOTAL as\n      a DTI-like ratio), explain exactly what was computed and how it differs from the standard\n      industry definition. Example: "Note: true DTI is typically monthly debt service divided by\n      monthly gross income; this dataset does not contain monthly figures, so the query used\n      total credit amount divided by total annual income as a rough proxy."\n   c. When in doubt, disclose. It is better to over-disclose than to present a derived number\n      as if it were a standard, directly-measured metric.\n2. No Extrapolation: Stick strictly to the numbers returned by the query. Do not extrapolate\n   findings about unmeasured variables. Frame any industry context strictly as general background\n   knowledge, never as an empirical finding from this data.\n3. Precision: Report numbers at reasonable precision (e.g. currency to the nearest unit,\n   percentages to one decimal place).\n\nQuestion: {question}\nSQL executed: {sql}\nQuery result: {result}\n\nAnswer:'
SQL_SELF_CORRECTION_PROMPT_V1 = 'The following SQL query failed.\n\nOriginal question: {question}\nSQL attempted: {sql}\nError: {error}\n\nTable: applicants\nColumns: {schema}\n\nRewrite this as a single, corrected SQL SELECT statement that fixes the error.\nOnly generate SELECT statements. Return ONLY the corrected SQL, no explanation.\nIf you need to substitute an unavailable field with a related valid metric from the schema, use a descriptive alias representing the actual metric used, never the invalid field name.\n\nCorrected SQL:'
SHAP_NARRATION_PROMPT_V1 = "You are a credit risk analyst assistant.\nAn ML model flagged an applicant with the following top risk drivers.\nEach line shows a feature name and its SHAP contribution value:\n  - POSITIVE values (e.g. +0.05) mean the feature INCREASED this applicant's default risk.\n  - NEGATIVE values (e.g. -0.03) mean the feature DECREASED this applicant's default risk (i.e. it is protective / favorable).\n\n{shap_summary}\n\nCRITICAL RULES:\n1. For each factor you mention, state clearly whether it INCREASED or DECREASED risk, based strictly on the sign of its SHAP value. Do NOT describe a negative-contribution feature as risk-increasing, or vice versa.\n2. Write one short, plain-language paragraph (2-3 sentences) suitable for a non-technical loan officer.\n3. Do not mention SHAP, features, machine learning, or code.\n\nExplanation:"

def build_nl_to_sql_prompt(question: str, schema: str) -> str:
    return NL_TO_SQL_PROMPT_V1.format(question=question, schema=schema)

def build_answer_prompt(question: str, result: str, sql: str='') -> str:
    return ANSWER_SYNTHESIS_PROMPT_V1.format(question=question, result=result, sql=sql)

def build_self_correction_prompt(question: str, sql: str, error: str, schema: str) -> str:
    return SQL_SELF_CORRECTION_PROMPT_V1.format(question=question, sql=sql, error=error, schema=schema)

def build_shap_narration_prompt(shap_summary: str) -> str:
    return SHAP_NARRATION_PROMPT_V1.format(shap_summary=shap_summary)